### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by f9n** [TurkishCheatSheets/MySQLCheatSheet#4]
Merhaba,
Üşenmemişsiniz yazmişsiniz, teşekkür ederim. Sakincasi yoksa her repo bulunan cheat sheet'leri Readme.md taşisaniz olur mu? Çünkü Cheat Sheet görmek icin dosyaya tikliyorum ve github'in geri dönmesini bekliyorum. Biraz sinir bozucu :)) 
https://github.com/TurkishCheatSheets/LinuxCheatSheet
https://github.com/TurkishCheatSheets/MySQLCheatSheet

**Comment by mertcangokgoz** [comment]
Bu düzenlemeyi bir kaç gün içerisinde yapalım 👍  Öneriniz için teşekkür ederim.
